FE-487 BLE-centralization of code and code optimizations
WeatherXM/wxm-android pull request #1
Opened 2024-01-18 10:33 UTC by PavlosTze

## **Why?**

In multiple view models the functions of scan, connect, pair, disconnect share the same code more or less. Explore potential centralization of that code in order to have a central source of truth.

### **How?**
1. Create `open class BluetoothHeliumViewModel` which acts as a base class for Claim, Reboot, Change Frequency, OTA of Helium `ViewModels` respectively.
2. That base class is responsible for scanning internally and connecting to a specific station and exposes the **open** functions `onPaired`, `onNotPaired`, `onScanFailure`, `onConnected` and `onConnectionFailure` which will be overridden by the view models in order to use them respectively.
3. Reboot, Change Frequency and OTA ViewModels use the full functionality of `BluetoothHeliumViewModel` for their own purposes and only deal with UI-related stuff based on the result, whereas all Claim-related ViewModels of Helium do the scanning on their own and use only the "Connection" part of the `BluetoothHeliumViewModel`.

### **Testing**

Test all BLE-related functionalities, try with different combinations (paired vs non-paired):
1. Claiming of Helium (we want BLE-related to be OK, and get an error at the end that device is already claimed)
4. Reboot of Helium Station (through station settings)
5. Device OTA of Helium Station (through station settings, in order to enable it set the `if` as `true` in `DeviceSettingsViewModel.kt` lines 223)
6. Change Frequency of Helium Station (through station settings)

2024-01-29 11:06 UTC, JohnFrontzos requested changes
Well structured Pavlos! I have commented some minor changes only.  
Also, would prefer something else for the "need to overridden" open fun, but I don't have any other solution at the moment.

2024-01-29 12:30 UTC, PavlosTze commented on app/src/main/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairViewModel.kt
> +) : BluetoothHeliumViewModel("", null, connectionUseCase, analytics) {
@JohnFrontzos Not sure what you mean, this doesn't work. Maybe you meant to define a `const val EMPTY_STRING = ""` ?

2024-01-29 12:39 UTC, PavlosTze commented on app/src/main/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairViewModel.kt
>      init {
There is no problem regarding the two `init`, they are different, the one in the Base class checks for the pairing status, which is only invoked after the scanning is completed (which the `init` in that ViewModel deals with).

2024-01-29 13:30 UTC, JohnFrontzos commented on app/src/main/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairViewModel.kt
> +) : BluetoothHeliumViewModel("", null, connectionUseCase, analytics) {
I mean something like fun String.empty() = "", in a single file and would be reused from there

2024-01-29 13:32 UTC, PavlosTze commented on app/src/main/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairViewModel.kt
> +) : BluetoothHeliumViewModel("", null, connectionUseCase, analytics) {
I already checked it, that doesn't work in our case. We don't have a string beforehand to do that

2024-01-31 13:17 UTC, pantelisss approved these changes
Codewise seems ok, could not tested on real device

2024-02-05 09:19 UTC, JohnFrontzos approved these changes

2024-02-09 09:38 UTC, merged