Photo verification intro screen
WeatherXM/wxm-android pull request #429
Opened 2024-12-04 16:18 UTC by PavlosTze

### **Why?**
Implement the introductory screen for the Photo Verification feature. This screen includes:
- Instructions on taking photos (including recommended angles or views) with images as an example
- A Terms of Service checkbox that unlocks the Start Photo Verification button
- A Start Photo Verification button to initiate the photo capture process.
- Use the same screen when coming from the Gallery screen (change the X button to back arrow and remove the agreement toggle button)

### **How?**
- Created `PhotoVerificationIntro` activity along with its layout and the respective fragment `PhotoVerificationInstructionsFragment` which will be reused in a next iteration to be opened in a `BottomSheetDialog` as well.
- Navigate to the above screen on claiming results
- Created a `PhotoExampleAdapter` which populates the respective `RecyclerView` with the `PhotoExample` UI Model which has an image and the texts below that image per the designs

### **Testing**
Complete a **mock** claiming flow and at the last screen continue to photo verification to view the screen and ensure everything is OK.

2024-12-06 14:53 UTC, pantelisss requested changes
It looks good, some minor things to tackle and we are good to go
- I was expecting that the examples scroller would be visible on both sides, now it's clipped on the left. I don't know if it's possible on Android
- The "Upload your photos" title is missing from the bottom of the scroller

2024-12-06 15:52 UTC, PavlosTze commented
Good catches @pantelisss , fixed!

2024-12-09 07:16 UTC, pantelisss commented
Looks good!

2024-12-09 07:16 UTC, pantelisss approved these changes

2024-12-09 07:20 UTC, merged